# Generated by Django 3.0.6 on 2020-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_machine', '0002_auto_20200511_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='pin_number',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
